###
//login
POST http://localhost:4000/api/users/login
Content-Type: application/json

{
  "username" : "amirhoseinh73",
  "password" : "123456"
}

###
//register
POST http://localhost:4000/api/users/register
Content-Type: application/json

{
  "firstname": "amirhosein",
  "lastname" : "hasani",
  "username" : "amirhoseinh73",
  "mobile"  : "09376885515",
  "password" : "123456"
}

###
// logout
GET http://localhost:4000/api/users/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzM5YjFiN2FiMGQ3YmZiNGFmZDVmYSIsInVzZXJuYW1lIjoiYW1pcmhvc2Vpbmg3MyIsImlhdCI6MTY3Mzc2NTU1MCwiZXhwIjoxNjczODUxOTUwfQ.K7-3vn0JdL7Nktslr6ulxMs5Fqs_hs12kOsP1fX1MVM

###
// user info
GET http://localhost:4000/api/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzRmZDkxNjIxMmEyYmI1YzgyOTY1NyIsInVzZXJuYW1lIjoiYW1pcmhvc2Vpbmg3MyIsImlhdCI6MTY3Mzg1NDM3MCwiZXhwIjoxNjczOTQwNzcwfQ.A4JGAMvzHmUFC_QNX5wlISWZ_k4y3vb7pTLjfoCzGuY

###
// update password
PATCH http://localhost:4000/api/users/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzRmZDkxNjIxMmEyYmI1YzgyOTY1NyIsInVzZXJuYW1lIjoiYW1pcmhvc2Vpbmg3MyIsImlhdCI6MTY3Mzg1NDM3MCwiZXhwIjoxNjczOTQwNzcwfQ.A4JGAMvzHmUFC_QNX5wlISWZ_k4y3vb7pTLjfoCzGuY

{
  "old_password" : "123456",
  "new_password" : "123456"
}

###
// update user info
PATCH http://localhost:4000/api/users/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzM5YjFiN2FiMGQ3YmZiNGFmZDVmYSIsInVzZXJuYW1lIjoiYW1pcmhvc2Vpbmg3MyIsImlhdCI6MTY3Mzc2NTU1MCwiZXhwIjoxNjczODUxOTUwfQ.K7-3vn0JdL7Nktslr6ulxMs5Fqs_hs12kOsP1fX1MVM

{
  "firstname": "amirhossein"
}

###
// admin get users list
GET http://localhost:4000/api/users/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYjU3ZTZkMmMwZTliNzBjZGVjZjE5NiIsInVzZXJuYW1lIjoiYW1pcmhvc2Vpbmg3MyIsImlhdCI6MTY3MzE2OTMxMCwiZXhwIjoxNjczMTY5NDEwfQ.n_-g4Ub3rndvVQYpIcClKpVo8qvx_F3jtH2OJ--gUvY

###
// admin delete specific user
DELETE http://localhost:4000/api/users/id
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYjU3ZTZkMmMwZTliNzBjZGVjZjE5NiIsInVzZXJuYW1lIjoiYW1pcmhvc2Vpbmg3MyIsImlhdCI6MTY3MzE2OTMxMCwiZXhwIjoxNjczMTY5NDEwfQ.n_-g4Ub3rndvVQYpIcClKpVo8qvx_F3jtH2OJ--gUvY


###
// get All projects
GET http://localhost:4000/api/project/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzRmZDkxNjIxMmEyYmI1YzgyOTY1NyIsInVzZXJuYW1lIjoiYW1pcmhvc2Vpbmg3MyIsImlhdCI6MTY3Mzg1NDM3MCwiZXhwIjoxNjczOTQwNzcwfQ.A4JGAMvzHmUFC_QNX5wlISWZ_k4y3vb7pTLjfoCzGuY

###
// save project
POST http://localhost:4000/api/project/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzRmZDkxNjIxMmEyYmI1YzgyOTY1NyIsInVzZXJuYW1lIjoiYW1pcmhvc2Vpbmg3MyIsImlhdCI6MTY3Mzg1NDM3MCwiZXhwIjoxNjczOTQwNzcwfQ.A4JGAMvzHmUFC_QNX5wlISWZ_k4y3vb7pTLjfoCzGuY

{
  "title": "b",
  "data": {"test": "1234"}
}

###
// get project
GET http://localhost:4000/api/project/63c5099fbdc21b1644fc905a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzRmZDkxNjIxMmEyYmI1YzgyOTY1NyIsInVzZXJuYW1lIjoiYW1pcmhvc2Vpbmg3MyIsImlhdCI6MTY3Mzg1NDM3MCwiZXhwIjoxNjczOTQwNzcwfQ.A4JGAMvzHmUFC_QNX5wlISWZ_k4y3vb7pTLjfoCzGuY

###
// update project
PATCH http://localhost:4000/api/project/63c5099fbdc21b1644fc905a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzRmZDkxNjIxMmEyYmI1YzgyOTY1NyIsInVzZXJuYW1lIjoiYW1pcmhvc2Vpbmg3MyIsImlhdCI6MTY3Mzg1NDM3MCwiZXhwIjoxNjczOTQwNzcwfQ.A4JGAMvzHmUFC_QNX5wlISWZ_k4y3vb7pTLjfoCzGuY

{
  "title": "b",
  "data": {"amirhosein":"hasani"}
}

###
// delete project
DELETE http://localhost:4000/api/project/63c5087abc785ddfe8c3874d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzRmZDkxNjIxMmEyYmI1YzgyOTY1NyIsInVzZXJuYW1lIjoiYW1pcmhvc2Vpbmg3MyIsImlhdCI6MTY3Mzg1NDM3MCwiZXhwIjoxNjczOTQwNzcwfQ.A4JGAMvzHmUFC_QNX5wlISWZ_k4y3vb7pTLjfoCzGuY