###
//login
POST http://192.168.1.10:4000/api/user/login
Content-Type: application/json

{
  "username" : "amirhoseinh73",
  "password" : "123456"
}

###
//register
POST http://localhost:4000/api/user/register
Content-Type: application/json

{
  "firstname": "amirhosein",
  "lastname" : "hasani",
  "username" : "amirhoseinh73",
  "mobile"  : "09376885515",
  "password" : "123456"
}

###
// logout
GET http://localhost:4000/api/user/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzM5YjFiN2FiMGQ3YmZiNGFmZDVmYSIsInVzZXJuYW1lIjoiYW1pcmhvc2Vpbmg3MyIsImlhdCI6MTY3Mzc2NTU1MCwiZXhwIjoxNjczODUxOTUwfQ.K7-3vn0JdL7Nktslr6ulxMs5Fqs_hs12kOsP1fX1MVM

###
// user info
GET http://localhost:4000/api/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzdlNTc2YWNmOGI0YWFiZmVlNGE4OCIsInVzZXJuYW1lIjoiYW1pcmhvc2Vpbmg3MyIsImlhdCI6MTY3NDA0NDc5NiwiZXhwIjoxNjc0MTMxMTk2fQ._EU1kjw8ZXt_8N4IUreuhd2wsM6cFVOBBnCR4aUTYcw

###
// update password
PATCH http://localhost:4000/api/user/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzdlNTc2YWNmOGI0YWFiZmVlNGE4OCIsInVzZXJuYW1lIjoiYW1pcmhvc2Vpbmg3MyIsImlhdCI6MTY3NDA0NDc5NiwiZXhwIjoxNjc0MTMxMTk2fQ._EU1kjw8ZXt_8N4IUreuhd2wsM6cFVOBBnCR4aUTYcw

{
  "old_password" : "123456",
  "new_password" : "123456"
}

###
// update user info
PATCH http://localhost:4000/api/user/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzdlNTc2YWNmOGI0YWFiZmVlNGE4OCIsInVzZXJuYW1lIjoiYW1pcmhvc2Vpbmg3MyIsImlhdCI6MTY3NDA0NDc5NiwiZXhwIjoxNjc0MTMxMTk2fQ._EU1kjw8ZXt_8N4IUreuhd2wsM6cFVOBBnCR4aUTYcw

{
  "firstname": "amirhossein"
}

###
// admin get user list
GET http://localhost:4000/api/user/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzdlNTc2YWNmOGI0YWFiZmVlNGE4OCIsInVzZXJuYW1lIjoiYW1pcmhvc2Vpbmg3MyIsImlhdCI6MTY3NDA0NDc5NiwiZXhwIjoxNjc0MTMxMTk2fQ._EU1kjw8ZXt_8N4IUreuhd2wsM6cFVOBBnCR4aUTYcw

###
// admin delete specific user
DELETE http://localhost:4000/api/user/id
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYjU3ZTZkMmMwZTliNzBjZGVjZjE5NiIsInVzZXJuYW1lIjoiYW1pcmhvc2Vpbmg3MyIsImlhdCI6MTY3MzE2OTMxMCwiZXhwIjoxNjczMTY5NDEwfQ.n_-g4Ub3rndvVQYpIcClKpVo8qvx_F3jtH2OJ--gUvY


###
// get All projects
GET http://localhost:4000/api/project/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzY2JiNTQxMGQwMTc5NWNjMWEwM2RhNiIsInVzZXJuYW1lIjoiYW1pcmhvc2Vpbmg3MyIsImlhdCI6MTY3NDM4MTg5MiwiZXhwIjoxNjc0NDY4MjkyfQ.idrp5SYk_5_WHRFKJWY7BpKsuIYi5fPnCR6zh-Lmxls

###
// save project
POST http://localhost:4000/api/project/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzY2JiNTQxMGQwMTc5NWNjMWEwM2RhNiIsInVzZXJuYW1lIjoiYW1pcmhvc2Vpbmg3MyIsImlhdCI6MTY3NDI5NDU5NSwiZXhwIjoxNjc0MzgwOTk1fQ.ZdMC2lXASqMf8wSn-ag5-Jjuesaq3KGscytCsv7DZOc

{
  "title": "b",
  "data": {"test": "1234"}
}

###
// get project
GET http://localhost:4000/api/project/63c7e62facf8b4aabfee4a99
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzdlNTc2YWNmOGI0YWFiZmVlNGE4OCIsInVzZXJuYW1lIjoiYW1pcmhvc2Vpbmg3MyIsImlhdCI6MTY3NDA0NDc5NiwiZXhwIjoxNjc0MTMxMTk2fQ._EU1kjw8ZXt_8N4IUreuhd2wsM6cFVOBBnCR4aUTYcw

###
// update project
PATCH http://localhost:4000/api/project/63cbb5620d01795cc1a03dae
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzY2JiNTQxMGQwMTc5NWNjMWEwM2RhNiIsInVzZXJuYW1lIjoiYW1pcmhvc2Vpbmg3MyIsImlhdCI6MTY3NDM4MTg5MiwiZXhwIjoxNjc0NDY4MjkyfQ.idrp5SYk_5_WHRFKJWY7BpKsuIYi5fPnCR6zh-Lmxls

{
  "title": "b",
  "data": {"amirhosein":"hasani"}
}

###
// delete project
DELETE http://localhost:4000/api/project/63c7e62bacf8b4aabfee4a96
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzdlNTc2YWNmOGI0YWFiZmVlNGE4OCIsInVzZXJuYW1lIjoiYW1pcmhvc2Vpbmg3MyIsImlhdCI6MTY3NDA0NDc5NiwiZXhwIjoxNjc0MTMxMTk2fQ._EU1kjw8ZXt_8N4IUreuhd2wsM6cFVOBBnCR4aUTYcw

###
// get All scenes
GET http://localhost:4000/api/project/list/scene/63cbb5620d01795cc1a03dae
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzY2JiNTQxMGQwMTc5NWNjMWEwM2RhNiIsInVzZXJuYW1lIjoiYW1pcmhvc2Vpbmg3MyIsImlhdCI6MTY3NDM4MTg5MiwiZXhwIjoxNjc0NDY4MjkyfQ.idrp5SYk_5_WHRFKJWY7BpKsuIYi5fPnCR6zh-Lmxls

###
// save scene
POST http://localhost:4000/api/scene/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzY2JiNTQxMGQwMTc5NWNjMWEwM2RhNiIsInVzZXJuYW1lIjoiYW1pcmhvc2Vpbmg3MyIsImlhdCI6MTY3NDI5NDU5NSwiZXhwIjoxNjc0MzgwOTk1fQ.ZdMC2lXASqMf8wSn-ag5-Jjuesaq3KGscytCsv7DZOc

{
  "project_id" : "63cbb5620d01795cc1a03dae",
  "title": "c",
  "data": {"test": "1234"}
}

###
// get scene
GET http://localhost:4000/api/scene/63cd04b649e7fa8479aa3202
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzY2JiNTQxMGQwMTc5NWNjMWEwM2RhNiIsInVzZXJuYW1lIjoiYW1pcmhvc2Vpbmg3MyIsImlhdCI6MTY3NDM4MTg5MiwiZXhwIjoxNjc0NDY4MjkyfQ.idrp5SYk_5_WHRFKJWY7BpKsuIYi5fPnCR6zh-Lmxls

###
// update scene
PATCH http://localhost:4000/api/scene/63c7ec75c8642c8c5e5be759
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzdlNTc2YWNmOGI0YWFiZmVlNGE4OCIsInVzZXJuYW1lIjoiYW1pcmhvc2Vpbmg3MyIsImlhdCI6MTY3NDA0NDc5NiwiZXhwIjoxNjc0MTMxMTk2fQ._EU1kjw8ZXt_8N4IUreuhd2wsM6cFVOBBnCR4aUTYcw

{
  "project_id" : "63c7e62facf8b4aabfee4a99",
  "title": "b",
  "data": {"mydata":"scene"}
}

###
// delete scene
DELETE http://localhost:4000/api/scene/63c7efd5a2e6a30a4aae4aa6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzdlNTc2YWNmOGI0YWFiZmVlNGE4OCIsInVzZXJuYW1lIjoiYW1pcmhvc2Vpbmg3MyIsImlhdCI6MTY3NDA0NDc5NiwiZXhwIjoxNjc0MTMxMTk2fQ._EU1kjw8ZXt_8N4IUreuhd2wsM6cFVOBBnCR4aUTYcw

###
PATCH http://localhost:4000/api/scene/upload/video/63cbbe49d136131e1b64e236
Content-Type: multipart/form-data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzdlNTc2YWNmOGI0YWFiZmVlNGE4OCIsInVzZXJuYW1lIjoiYW1pcmhvc2Vpbmg3MyIsImlhdCI6MTY3NDA0NDc5NiwiZXhwIjoxNjc0MTMxMTk2fQ._EU1kjw8ZXt_8N4IUreuhd2wsM6cFVOBBnCR4aUTYcw

{
  "video": "file" // video/mp4
}

###
PATCH http://localhost:4000/api/scene/upload/image/63cbbe49d136131e1b64e236
Content-Type: multipart/form-data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzdlNTc2YWNmOGI0YWFiZmVlNGE4OCIsInVzZXJuYW1lIjoiYW1pcmhvc2Vpbmg3MyIsImlhdCI6MTY3NDA0NDc5NiwiZXhwIjoxNjc0MTMxMTk2fQ._EU1kjw8ZXt_8N4IUreuhd2wsM6cFVOBBnCR4aUTYcw

{
  "image": "file" // image/jpg, image/jpeg, image/png, image/gif
}