###
//login
POST http://localhost:4000/api/users/login
Content-Type: application/json

{
  "username" : "amirhoseinh73",
  "password" : "123456"
}

###
//register
POST http://localhost:4000/api/users/register
Content-Type: application/json

{
  "firstname": "amirhosein",
  "lastname" : "hasani",
  "username" : "amirhoseinh73",
  "mobile"  : "09376885515",
  "password" : "123456"
}

###
// logout
GET http://localhost:4000/api/users/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzM5YjFiN2FiMGQ3YmZiNGFmZDVmYSIsInVzZXJuYW1lIjoiYW1pcmhvc2Vpbmg3MyIsImlhdCI6MTY3Mzc2NTU1MCwiZXhwIjoxNjczODUxOTUwfQ.K7-3vn0JdL7Nktslr6ulxMs5Fqs_hs12kOsP1fX1MVM

###
// user info
GET http://localhost:4000/api/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzdlNTc2YWNmOGI0YWFiZmVlNGE4OCIsInVzZXJuYW1lIjoiYW1pcmhvc2Vpbmg3MyIsImlhdCI6MTY3NDA0NDc5NiwiZXhwIjoxNjc0MTMxMTk2fQ._EU1kjw8ZXt_8N4IUreuhd2wsM6cFVOBBnCR4aUTYcw

###
// update password
PATCH http://localhost:4000/api/users/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzdlNTc2YWNmOGI0YWFiZmVlNGE4OCIsInVzZXJuYW1lIjoiYW1pcmhvc2Vpbmg3MyIsImlhdCI6MTY3NDA0NDc5NiwiZXhwIjoxNjc0MTMxMTk2fQ._EU1kjw8ZXt_8N4IUreuhd2wsM6cFVOBBnCR4aUTYcw

{
  "old_password" : "123456",
  "new_password" : "123456"
}

###
// update user info
PATCH http://localhost:4000/api/users/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzdlNTc2YWNmOGI0YWFiZmVlNGE4OCIsInVzZXJuYW1lIjoiYW1pcmhvc2Vpbmg3MyIsImlhdCI6MTY3NDA0NDc5NiwiZXhwIjoxNjc0MTMxMTk2fQ._EU1kjw8ZXt_8N4IUreuhd2wsM6cFVOBBnCR4aUTYcw

{
  "firstname": "amirhossein"
}

###
// admin get users list
GET http://localhost:4000/api/users/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzdlNTc2YWNmOGI0YWFiZmVlNGE4OCIsInVzZXJuYW1lIjoiYW1pcmhvc2Vpbmg3MyIsImlhdCI6MTY3NDA0NDc5NiwiZXhwIjoxNjc0MTMxMTk2fQ._EU1kjw8ZXt_8N4IUreuhd2wsM6cFVOBBnCR4aUTYcw

###
// admin delete specific user
DELETE http://localhost:4000/api/users/id
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYjU3ZTZkMmMwZTliNzBjZGVjZjE5NiIsInVzZXJuYW1lIjoiYW1pcmhvc2Vpbmg3MyIsImlhdCI6MTY3MzE2OTMxMCwiZXhwIjoxNjczMTY5NDEwfQ.n_-g4Ub3rndvVQYpIcClKpVo8qvx_F3jtH2OJ--gUvY


###
// get All projects
GET http://localhost:4000/api/project/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzdlNTc2YWNmOGI0YWFiZmVlNGE4OCIsInVzZXJuYW1lIjoiYW1pcmhvc2Vpbmg3MyIsImlhdCI6MTY3NDA0NDc5NiwiZXhwIjoxNjc0MTMxMTk2fQ._EU1kjw8ZXt_8N4IUreuhd2wsM6cFVOBBnCR4aUTYcw

###
// save project
POST http://localhost:4000/api/project/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzdlNTc2YWNmOGI0YWFiZmVlNGE4OCIsInVzZXJuYW1lIjoiYW1pcmhvc2Vpbmg3MyIsImlhdCI6MTY3NDA0NDc5NiwiZXhwIjoxNjc0MTMxMTk2fQ._EU1kjw8ZXt_8N4IUreuhd2wsM6cFVOBBnCR4aUTYcw

{
  "title": "b",
  "data": {"test": "1234"}
}

###
// get project
GET http://localhost:4000/api/project/63c7e62facf8b4aabfee4a99
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzdlNTc2YWNmOGI0YWFiZmVlNGE4OCIsInVzZXJuYW1lIjoiYW1pcmhvc2Vpbmg3MyIsImlhdCI6MTY3NDA0NDc5NiwiZXhwIjoxNjc0MTMxMTk2fQ._EU1kjw8ZXt_8N4IUreuhd2wsM6cFVOBBnCR4aUTYcw

###
// update project
PATCH http://localhost:4000/api/project/63c7e62facf8b4aabfee4a99
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzdlNTc2YWNmOGI0YWFiZmVlNGE4OCIsInVzZXJuYW1lIjoiYW1pcmhvc2Vpbmg3MyIsImlhdCI6MTY3NDA0NDc5NiwiZXhwIjoxNjc0MTMxMTk2fQ._EU1kjw8ZXt_8N4IUreuhd2wsM6cFVOBBnCR4aUTYcw

{
  "title": "b",
  "data": {"amirhosein":"hasani"}
}

###
// delete project
DELETE http://localhost:4000/api/project/63c7e62bacf8b4aabfee4a96
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzdlNTc2YWNmOGI0YWFiZmVlNGE4OCIsInVzZXJuYW1lIjoiYW1pcmhvc2Vpbmg3MyIsImlhdCI6MTY3NDA0NDc5NiwiZXhwIjoxNjc0MTMxMTk2fQ._EU1kjw8ZXt_8N4IUreuhd2wsM6cFVOBBnCR4aUTYcw