GET http://localhost:4000/users

###
GET http://localhost:4000/users/63b57e6d2c0e9b70cdecf196

###
POST http://localhost:4000/users
Content-Type: application/json

{
  "firstname": "amirhosein",
  "lastname" : "hasani",
  "username" : "amirhoseinh73",
  "mobile"  : "09376885515",
  "password" : "123456"
}

###
POST http://localhost:4000/users/login
Content-Type: application/json

{
  "username" : "amirhoseinh73",
  "password" : "123456"
}

###
DELETE http://localhost:4000/users/63b53c6d38e0ce2aa62f8e3d

###
PATCH http://localhost:4000/users/63b57e6d2c0e9b70cdecf196
Content-Type: application/json

{
  "firstname": "amirhossein"
}